bookings/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
  #  url(r'^$', views.showOptions, name='showOptions'),
    url(r'^$',views.BookMachine, name='BookMachine'),
#    url(r'^unbook/(?P<machine_name>\w+)/(?P<booked_date>\d{8)/(P<booked_time>\d{2})/$', views.UnbookMachine, name='UnbookMachine'),
    url(r'^unbook/(?P<machine_name>\w+)/(?P<booked_date>\d{8})/(?P<booked_time>\w+)$', views.UnbookMachine, name='UnbookMachine'),
    url(r'^tomorrow/$',views.BookMachineTmr,name='BookMachineTmr'),

)

swt/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'swt.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    (r'^$', 'profiles.views.home'),
	(r'^login/', 'auth.django_cas.views.login'),
   #(r'^profiles/', include('profiles.urls')),
   # url(r'^getuser/', 'profiles.views.getUser'),
    url(r'^home/$', 'profiles.views.home'),
    url(r'^register/$', 'profiles.views.newProfile'),
    (r'^profiles/', include('profiles.urls')),
    url(r'^friends/$', 'profiles.views.home'),
    url(r'^friends/(?P<friend_id>\w+)/$', 'profiles.views.viewFriend'),
    (r'^workouts/', include('workouts.urls')),
    (r'^logintest/','auth.django_cas.views.logintest'),
    url(r'^admin/', include(admin.site.urls)),
    (r'^logout/','auth.django_cas.views.logout',{'next_page':'/swt/'}),
    #(r'^reservation/',include('bookings.django_reservations.reservations.urls')),
    #url(r'^search/', include('bookings.urls')),
    #url(r'^reservations/', include('bookings_test.reservations.urls')),
   # url(r'^country/', include('bookings.urls')),
    #url(r'^booking/booking/',include('booking.urls')),
    url(r'^bookings/',include('bookings.urls')),
#    url(r'^image_test/',include('image_test.urls')),
)

bookings/models.py
from django.db import models
from datetime import datetime


# Create your models here.
class Bookings(models.Model):
    machine_name=models.CharField(max_length=50)
    booked_date=models.DateField()
    booked_time=models.CharField(max_length=2)
    username=models.CharField(max_length=50)    
    
    @classmethod
    def create_range(self, avail_times):
	formated=[]
	for i in range(len(avail_times)):
            startrange_val=avail_times[i]
            formated.append(startrange_val)
            formated.append(startrange_val+1)
        return formated

    @classmethod
    def format_range(self, avail_times):
	formated=[]
	for i in range(0,len(avail_times),2):
            formated.append(str(avail_times[i])+":00"+ "-"+str(avail_times[i+1])+":00")
        return formated

    @classmethod
    def get_delta_index(self, booked_times):
	i=0
	while (booked_times[i]==1):
            i=i+1
        return i

    @classmethod
    #returns an array with possitins where pos 0 is 6am 
    #if value at pos is 1 that means that at that time everythingis fully booked
    def fully_booked_arr(self,booked_date,machine_name):
	result=[0]*15
	total_machines=0
	if(machine_name=='stairs'):
            temp= Machines.objects.get(machine_name='stairs')
	    total_machines=temp.available
	elif(machine_name=='treadmill'):
	    temp= Machines.objects.get(machine_name='treadmill')
	    total_machines=temp.available
	else:
	    temp= Machines.objects.get(machine_name='rowing')
	    total_machines=temp.available

        for time in range(6,21):
	    if(Bookings.objects.filter(booked_date=booked_date,machine_name=machine_name,booked_time=time).count()>=total_machines):
	        result[time-6]=1
        return result

class Machines(models.Model):
      machine_name=models.CharField(max_length=20)
      available=models.IntegerField()

bookings/forms.py
from django import forms
from bookings.models import Bookings
from django.forms.extras.widgets import SelectDateWidget
from django.forms.fields import DateField, ChoiceField, MultipleChoiceField
from django.forms.widgets import RadioSelect, CheckboxSelectMultiple


OPEN_TIMES = (
	('6', '6:00-7:00'),
	('7', '7:00-8:00'),
	('8', '8:00-9:00'),
	('9', '9:00-10:00'),
	('10', '10:00-11:00'),
	('11', '11:00-12:00'),
	('12', '12:00-13:00'),
	('13', '13:00-14:00'),
	('14', '14:00-15:00'),
	('15', '15:00-16:00'),
	('16', '16:00-17:00'),
	('17', '17:00-18:00'),
	('18', '18:00-19:00'),
	('19', '19:00-20:00'),
	('20', '20:00-21:00'),
)

MACHINE_TYPES = (
	('rowing', 'Rowing Machine'),
	('stairs', 'Stairs Machine'),
	('treadmill', 'Treadmill'),
)


class AddBookingForm(forms.ModelForm):
	machine_name = forms.ChoiceField(choices=MACHINE_TYPES)
	treadmill_time = forms.ChoiceField(choices=OPEN_TIMES)
	stairs_time = forms.ChoiceField(choices=OPEN_TIMES)
	rowing_time = forms.ChoiceField(choices=OPEN_TIMES)

	class Meta:
		model = Bookings
		fields = ('machine_name', 'treadmill_time', 'stairs_time', 'rowing_time',)

	def __init__(self, *args, **kwargs):
		super(AddBookingForm, self).__init__(*args, **kwargs)
		#treadmill_time= kwargs.pop("treadmill_time")
		for field_name in self.fields:
			field = self.fields[field_name]
			field.widget.attrs.update({
				'class': 'form-control input-sm'
			})
		#self.fields['treadmill_time']= forms.ChoiceFields(choices=treadmill_time)


class DeleteBookingsForm(forms.ModelForm):
       class Meta:
           model= Bookings
           fields=('machine_name','booked_time','booked_date',)
	   exclude=('username',)        


class AddBookingFormTomorrow(forms.ModelForm):
	machine_name_tmr = forms.ChoiceField(choices=MACHINE_TYPES)
        treadmill_time_tmr = forms.ChoiceField(choices=OPEN_TIMES)
        stairs_time_tmr = forms.ChoiceField(choices=OPEN_TIMES)
        rowing_time_tmr = forms.ChoiceField(choices=OPEN_TIMES)

        class Meta:
                model = Bookings
                fields = ('machine_name_tmr', 'treadmill_time_tmr', 'stairs_time_tmr', 'rowing_time_tmr',)

        def __init__(self, *args, **kwargs):
                super(AddBookingFormTomorrow, self).__init__(*args, **kwargs)
                #treadmill_time= kwargs.pop("treadmill_time")
                for field_name in self.fields:
                        field = self.fields[field_name]
                        field.widget.attrs.update({
                                'class': 'form-control input-sm'
                        })

bookings/views.py
import os
from django.shortcuts import render, render_to_response
from bookings.models import Bookings
from django.core.context_processors import csrf
from bookings.forms import AddBookingForm ,DeleteBookingsForm , AddBookingFormTomorrow
import datetime
from django.http import HttpResponseRedirect , HttpResponse
from profiles.declarators import swtLoginReq
from time import strftime
from datetime import timedelta

# Create your views here.

@swtLoginReq
def BookMachine(request):
    #query everything that it is available to use today during the whole day until gym closes. assume it clos$
    #everything is done ine simple 24 hours format so 1 is 1 am 13 is 1 pm ...
    #select current date #year month day
    curr_date=datetime.datetime.now()
    today=curr_date.strftime("%Y-%m-%d")
    tmr_date=datetime.datetime.today()+timedelta(days=1)
    tomorrow=tmr_date.strftime("%Y-%m-%d")
    time=strftime("%H")
    sfu_id=request.user.username
    multi_book=""
    if request.POST:
	#'id_machine_name' is passed via the form
	new_booking = Bookings(machine_name='id_machine_name',booked_date=today, username=sfu_id)
	form = AddBookingForm(request.POST, instance=new_booking)#try to add the bookings for today
	booked_time=""
  	if form.is_valid():
	    data = form.cleaned_data
	    if(data['machine_name']=='rowing'):
	        booked_time=data['rowing_time']

	    elif(data['machine_name']=='treadmill'):
	        booked_time=data['treadmill_time']

	    elif(data['machine_name']=='stairs'):
		booked_time=data['stairs_time']
	   
	    new_booking.booked_time=booked_time  
	    #check that user hasnt previoulsy booked that machine
	    booked_check=Bookings.objects.filter(machine_name=data['machine_name'],booked_date=today,username=sfu_id,booked_time=booked_time)

	    if(booked_check.count()>0):
	        return HttpResponseRedirect('/swt/bookings/')
	    else:	

	        form.save()

	        return HttpResponseRedirect('/swt/bookings/')

    else:
        form_today= AddBookingForm()	
	form_tomorrow=AddBookingFormTomorrow()	
    args={}
    args.update(csrf(request))
 
    #query database see what the user has booked for today
    my_bookings= Bookings.objects.filter(booked_date=today,username=sfu_id).order_by('booked_time')
    #assume that there are 2  machines of each type at the gym and we have to calculate how many machines are booked for each time
    fully_booked_treadmill=Bookings.fully_booked_arr(today,'treadmill')
    fully_booked_rowing=Bookings.fully_booked_arr(today,'rowing')
    fully_booked_stairs=Bookings.fully_booked_arr(today,'stairs')

    #now do the same types of query's but for tomorrow's date
    my_bookings_tmr=Bookings.objects.filter(booked_date=tomorrow,username=sfu_id).order_by('booked_time')
    #assume there are 2 machines of each time, if wished change number in the model function
    fully_booked_treadmill_tmr=Bookings.fully_booked_arr(tomorrow,'treadmill')
    fully_booked_rowing_tmr=Bookings.fully_booked_arr(tomorrow,'rowing')
    fully_booked_stairs_tmr=Bookings.fully_booked_arr(tomorrow,'stairs')
    #we may not need THIS
    booked_times_treadmill = []
    booked_times_stairs = []
    booked_times_rowing = []
    # The Default Index to start with in Booking Time Dropdown
    default_t_index = 6
    default_s_index = 6
    default_r_index = 6
    #tomorrows indexes
    default_t_index_tmr=6
    default_s_index_tmr=6
    default_r_index_tmr=6
    
    #calculatin the indexes for today
    default_t_index=default_t_index + Bookings.get_delta_index(fully_booked_treadmill)
    default_s_index=default_s_index + Bookings.get_delta_index(fully_booked_stairs)
    default_r_index=default_r_index + Bookings.get_delta_index(fully_booked_rowing)      
    #calculatin the index for tomorrow
    default_t_index_tmr=default_t_index_tmr+ Bookings.get_delta_index(fully_booked_treadmill_tmr)
    default_s_index_tmr=default_s_index_tmr+ Bookings.get_delta_index(fully_booked_stairs_tmr)
    default_r_index_tmr=default_r_index_tmr+ Bookings.get_delta_index(fully_booked_rowing_tmr)

    args['form_today'] = form_today
    args['booked_times_treadmill'] = booked_times_treadmill
    args['booked_times_stairs'] = booked_times_stairs
    args['booked_times_rowing'] = booked_times_rowing
    args['default_t_index'] = default_t_index
    args['default_s_index'] = default_s_index
    args['default_r_index'] = default_r_index 
    args['fully_booked_treadmill']=fully_booked_treadmill
    args['fully_booked_stairs']=fully_booked_stairs
    args['fully_booked_rowing']=fully_booked_rowing
    args['my_bookings']=my_bookings
    args['time']=int(time)
    #tomorrow variables and related 
    args['tomorrow']=tomorrow
    args['form_tomorrow']=form_tomorrow
    args['my_bookings_tmr']=my_bookings_tmr
    return render_to_response('bookmachine.html',args)

@swtLoginReq
def UnbookMachine(request,machine_name,booked_date,booked_time):
    sfu_id=request.user.username
    #convert the yearmonthday to good formated date
    fmt_date=str(booked_date[:4])+'-'+str(booked_date[4:6])+'-'+str(booked_date[6:8])
    booked_machine= Bookings.objects.get(machine_name=machine_name,booked_date=fmt_date,booked_time=booked_time,username=sfu_id)    
    #return HttpResponse(machine_name +fmt_date+sfu_id+ booked_time)
    # if booked_machine!=None:
    booked_machine.delete()
    return HttpResponseRedirect('/swt/bookings')



@swtLoginReq
def BookMachineTmr(request):
    #this function will only be called when we book machines for tomorrow this is a POST
    tmr_date=datetime.datetime.today()+timedelta(days=1)
    tomorrow=tmr_date.strftime("%Y-%m-%d")
    sfu_id=request.user.username
    if request.POST:
        #'id_machine_name' is passed via the form
        new_booking_tmr = Bookings(machine_name='id_machine_name',booked_date=tomorrow, username=sfu_id)
        form = AddBookingFormTomorrow(request.POST, instance=new_booking_tmr)#try to add the bookings for today
        booked_time=""
        if form.is_valid():
            data = form.cleaned_data
            if(data['machine_name_tmr']=='rowing'):
                booked_time=data['rowing_time_tmr']

            elif(data['machine_name_tmr']=='treadmill'):
                booked_time=data['treadmill_time_tmr']

            elif(data['machine_name_tmr']=='stairs'):
                booked_time=data['stairs_time_tmr']

            new_booking_tmr.booked_time=booked_time
	    new_booking_tmr.machine_name=data['machine_name_tmr']
            #check that user hasnt previoulsy booked that machine
            booked_check=Bookings.objects.filter(machine_name=data['machine_name_tmr'],booked_date=tomorrow,username=sfu_id,booked_time=booked_time)

            if(booked_check.count()>0):
                return HttpResponseRedirect('/swt/bookings/')
            else:

                form.save()

                return HttpResponseRedirect('/swt/bookings/')
    else:
	return HttpResponseRedirect('/swt/bookings')

bookings/templates/bookmachine.html
{% extends "base-default.html"%}
{% load static %}


{% block content %}
<div class="container-fluid">
	<div class="row-fluid">
		<!-- Booking Summary -->
		<div class="col-md-3">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">My Bookings</h3>
				</div>
				<div class="panel-body">
					<h4>Today</h4>
					{% if my_bookings|length != 0 %}
						{% for booking in my_bookings %}
						<p>
							{{ booking.machine_name|title }} Machine
							{{ booking.booked_time }}:00
							{{ booking.booked_date|date:"Y-n-j" }}
					    </p>
					    <form action="/swt/bookings/unbook/{{ booking.machine_name }}/{{ booking.booked_date|date:"Ymd" }}/{{ booking.booked_time }}" method="post">{% csrf_token %}
							<input class="btn btn-primary btn-sm col-md-offset-4" type="submit" name="submit" value="Cancel Booking">
						</form>
						{% endfor %}
					{% else %}
						<p>None</p>
					{% endif %}
					<!--Tomorrow's Bookings-->
					<h4>Tomorrow</h4>
					{% if my_bookings_tmr|length != 0 %}
						{%for booking in my_bookings_tmr %}
						<p>
							{{ booking.machine_name|title }} Machine
							{{ booking.booked_time }}:00
							{{ booking.booked_date|date:"Y-n-j" }}
						</p>   
						<form action="/swt/bookings/unbook/{{ booking.machine_name }}/{{ booking.booked_date|date:"Ymd" }}/{{ booking.booked_time}}" method="post">{% csrf_token %}
							<input class="btn btn-primary btn-sm col-md-offset-4" type="submit" name="submit" value="Cancel Booking">
						</form>	
						{% endfor %}
					{% else %}
						<p>None</p>
					{% endif %}
				</div>
			</div>
		</div>

		<div class="col-md-8">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Book a Workout Machine for Today</h3>
				</div>
				<div class="panel-body">
					{% if time > 20 %}
					   <p>Sorry, the Gym is closed now</p>
					{% else %}
					<!-- Book Machine Form -->
					<form class="form-horizontal" action="/swt/bookings/" method="post">{% csrf_token %}
						<div class="form-group">
							<label for="id_machine_name" class="col-md-2 control-label">Machine Type</label>
							<div class="col-md-3">{{ form_today.machine_name }}</div>
						</div>
						<div class="form-group hidden" id="div-treadmill-time">
							<label for="id_treadmill_time" class="col-md-2 control-label">Available Times</label>
							<div class="col-md-3">{{ form_today.treadmill_time }}</div>
							<img src=" http://syracusefitness.com/Treadmills/treadmills_pic.jpg" width="200" height="200">
						</div>
						<div class="form-group hidden" id="div-stairs-time">
							<label for="id_stairs_time" class="col-md-2 control-label">Available Times</label>
							<div class="col-md-3">{{ form_today.stairs_time }}</div>
							<img src="  http://images.amazon.com/images/G/01/stores/sport-goods/B001AS4YVC-handrails.jpg" width="200" height="200">
						</div>
						<div class="form-group hidden" id="div-rowing-time">
							<label for="id_rowing_time" class="col-md-2 control-label">Available Times</label>
							<div class="col-md-3">{{ form_today.rowing_time }}</div>
							<img src=" http://www.littleblokefitness.com.au/wp-content/uploads/wpsc/product_images/concept2%20model%20d%203.jpg" width="200" heigth="200">
						</div>
						<div class="form-group hidden" id="div-booking-submit">
							<input class="btn btn-primary btn-sm col-md-offset-4" type="submit" name="submit" value="Book Machine">
						</div>
					</form>
					{% endif %}
				</div>
			</div>

			<div class="panel panel-primary">
				<div class="panel-heading">
					<!-- Tomorrow related form-->
					<h3 class="panel-title">Book a Workout Machine for Tomorrow</h3>
				</div>
				<div class="panel-body">
					<!-- Book Machine Form: Tomorrow -->
					<form class="form-horizontal" action="/swt/bookings/tomorrow/" method="post">{% csrf_token %}
						<div class="form-group">
							<label for="id_machine_name" class="col-md-2 control-label">Machine Type</label>
							<div class="col-md-3">{{ form_tomorrow.machine_name_tmr }}</div>
						</div>
						<div class="form-group hidden" id="div-treadmill-time-tmr">
							<label for="id_treadmill_time" class="col-md-2 control-label">Available Times</label>
							<div class="col-md-3">{{ form_tomorrow.treadmill_time_tmr }}</div>
						</div>
						<div class="form-group hidden" id="div-stairs-time-tmr">
							<label for="id_stairs_time" class="col-md-2 control-label">Available Times</label>
							<div class="col-md-3">{{ form_tomorrow.stairs_time_tmr }}</div>
						</div>
						<div class="form-group hidden" id="div-rowing-time-tmr">
							<label for="id_rowing_time" class="col-md-2 control-label">Available Times</label>
							<div class="col-md-3">{{ form_tomorrow.rowing_time_tmr }}</div>
						</div>
						<div class="form-group hidden" id="div-booking-submit-tmr">
							<input class="btn btn-primary btn-sm col-md-offset-4" type="submit" name="submit_tmr" value="Book Machine">
						</div>
					</form>
				</div>
			</div>
		</div>

	</div>
</div>



<script type="text/javascript">

	{% for full in fully_booked_treadmill %}
		var value= {{ full }} ;
        	 {%if full == 1 %}
		    var counter= {{forloop.counter0}};
		    var timeslot_t = counter;//this will be the possition to hide 
	            var treadmillElement = document.getElementById('id_treadmill_time').getElementsByTagName('option')[timeslot_t];
                    treadmillElement.className= treadmillElement.className+ " hidden";
		 {% endif %}				
	{% endfor %}
	var offset_t = {{ default_t_index }} - 6;
        document.getElementById('id_treadmill_time').selectedIndex=offset_t;	
	
	{% for full in fully_booked_stairs %}
                var value= {{ full }} ;
                 {%if full == 1 %}
                    var counter= {{forloop.counter0}};
                    var timeslot_s = counter;//this will be the possition to hide
                    var stairsElement = document.getElementById('id_stairs_time').getElementsByTagName('option')[timeslot_s];
                    stairsElement.className= stairsElement.className+ " hidden";
                {% endif %}
        {% endfor %}
        var offset_s = {{ default_s_index }} - 6;
        document.getElementById('id_stairs_time').selectedIndex=offset_s;

	{% for full in fully_booked_rowing %}
                var value= {{ full }} ;
                 {%if full == 1 %}
                    var counter= {{forloop.counter0}};
                    var timeslot_r = counter;//this will be the possition to hide
                    var rowingElement = document.getElementById('id_rowing_time').getElementsByTagName('option')[timeslot_r];
                    rowingElement.className= rowingElement.className+ " hidden";
                {% endif %}
        {% endfor %}
        var offset_r = {{ default_r_index }} - 6;
        document.getElementById('id_rowing_time').selectedIndex=offset_r;
	

	//this removes the times that are before the current time
	//delete the time that has already past REMOVE THIS so its syncronized according to the time 
        var hour= new Date().getHours() -6;//replace this by {{time}}
        for(var i=0; i <hour; i++){
                var temp_t = document.getElementById('id_treadmill_time').getElementsByTagName('option')[i];
                temp_t.className= temp_t.className+ " hidden";
		var temp_s= document.getElementById('id_stairs_time').getElementsByTagName('option')[i];		
		temp_s.className= temp_s.className+ " hidden";
		var temp_r= document.getElementById('id_rowing_time').getElementsByTagName('option')[i];                
                temp_r.className= temp_r.className+ " hidden";
        }
	document.getElementById('id_rowing_time').selectedIndex=hour;
	document.getElementById('id_stairs_time').selectedIndex=hour;
	document.getElementById('id_treadmill_time').selectedIndex=hour;	



</script>

{% endblock %}

bookings/templates/sample.html
{%load static%}
{% load dajaxice_templatetags %}

<head>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script type="text/javascript" src=" http://tsimissoula.com/tsimissoula.com/system/extend/jquery_plugins/jquery.ba-serializeobject.min.js"></script>
<script type="text/javascript" src="/static/dajax/jquery.dajax.core.js"></script>
{% dajaxice_js_import %}

<script src="/static/dajax/jquery.dajax.core.js"></script>

<script type="text/javascript">
	Dajaxice.bookings.say_hello(Dajax.process);
</script>

<script src="/static/dajax/jquery.dajax.core.js" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript">
function calculate(){
    Dajaxice.bookings.multiply(Dajax.process,{'a':$('#a').val(),'b':$('#b').val()});

}
</script>
</head>

<body>
<h1>Sample Multiplier</h1>
<input type="text" value="5" id="a"> x
<input type="text" value="6" id="b"> =
<input type="text" value="" id="result">
<input type="button" value="Multiply!" onclick="calculate();">

</body>
</html>