profiles/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
    url(r'^$', views.myProfile, name='myProfile'),
    url(r'^new/$', views.newProfile, name='newProfile'),
    url(r'^edit/$', views.editProfile, name='editProfile'),
    url(r'^friend-request/$', views.requestFriend, name='requestFriend'),
    url(r'^friend-accept/(?P<friend_id>\w+)/$', views.acceptFriend, name='acceptFriend'),
    url(r'^friend-decline/(?P<friend_id>\w+)/$', views.declineFriend, name='declineFriend'),
    url(r'^friend-delete/(?P<friend_id>\w+)/$', views.deleteFriend, name='deleteFriend'),
	url(r'^friends/$', views.home, name='home'),
	url(r'^friends/(?P<friend_id>\w+)/$', views.viewFriend, name='viewFriend'),
)

swt/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'swt.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    (r'^$', 'profiles.views.home'),
	(r'^login/', 'auth.django_cas.views.login'),
   #(r'^profiles/', include('profiles.urls')),
   # url(r'^getuser/', 'profiles.views.getUser'),
    url(r'^home/$', 'profiles.views.home'),
    url(r'^register/$', 'profiles.views.newProfile'),
    (r'^profiles/', include('profiles.urls')),
    url(r'^friends/$', 'profiles.views.home'),
    url(r'^friends/(?P<friend_id>\w+)/$', 'profiles.views.viewFriend'),
    (r'^workouts/', include('workouts.urls')),
    (r'^logintest/','auth.django_cas.views.logintest'),
    url(r'^admin/', include(admin.site.urls)),
    (r'^logout/','auth.django_cas.views.logout',{'next_page':'/swt/'}),
    #(r'^reservation/',include('bookings.django_reservations.reservations.urls')),
    #url(r'^search/', include('bookings.urls')),
    #url(r'^reservations/', include('bookings_test.reservations.urls')),
   # url(r'^country/', include('bookings.urls')),
    #url(r'^booking/booking/',include('booking.urls')),
    url(r'^bookings/',include('bookings.urls')),
#    url(r'^image_test/',include('image_test.urls')),
)

profiles/models.py
from django.db import models
from django.core.signing import Signer
from django.core.exceptions import ValidationError
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from django.conf import settings


def validate_positive(value):
	if value < 1:
		raise ValidationError('%s must be positive.' % value)

def validate_length(value):
	if len(value) < 1:
		raise ValidationError('Please enter a valid value.')


# Create your models here.
class Profile(models.Model):
	username = models.CharField(max_length=50)
	first_name = models.CharField(max_length=50, validators=[validate_length])
	last_name = models.CharField(max_length=50, validators=[validate_length])
	weight = models.IntegerField(blank=True, null=True, validators=[validate_positive])
	height = models.IntegerField(blank=True, null=True, validators=[validate_positive])
	bio = models.TextField(blank=True, null=True)
	quote = models.TextField(blank=True, null=True)
	profile_pic = models.URLField(blank=True)
	completed = models.BooleanField(default=False)

	def __str__(self):
		return self.first_name + " " + self.last_name


class FriendList(models.Model):
    sender_id = models.CharField(max_length=50)
    receiver_id = models.CharField(max_length=50)
    accepted = models.BooleanField(default=False)
	

class GymStatus(models.Model):
	gym_area = models.CharField(max_length=50)
	status = models.CharField(max_length=50)
	last_modified_by = models.CharField(max_length=50)

profiles/forms.py
from django import forms
from profiles.models import Profile, FriendList, GymStatus


class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('first_name', 'last_name', 'weight', 'height', 'bio', 'quote', 'profile_pic')

	def __init__(self, *args, **kwargs):
		super(ProfileForm, self).__init__(*args, **kwargs)
		for field_name in self.fields:
			field = self.fields[field_name]
			field.widget.attrs.update({
				'class': 'form-control input-sm'
			})


class FriendsForm(forms.ModelForm):	
	class Meta:
		model = FriendList
		fields = ('receiver_id',)

	def __init__(self, *args, **kwargs):
		super(FriendsForm, self).__init__(*args, **kwargs)
		self.fields['receiver_id'].widget.attrs.update({
			'class': 'form-control input-sm',
			'id': 'inputSmall'
		})
	
	
class GymStatusForm(forms.ModelForm):
	class Meta:
		model = GymStatus
		fields = ('gym_area', 'status')

profiles/views.py
import datetime

from django.shortcuts import render_to_response
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from django.core.signing import Signer
from time import strftime
import urllib

from chartit import DataPool, Chart

from profiles.models import Profile, FriendList, GymStatus
from profiles.forms import ProfileForm, FriendsForm
from profiles.declarators import swtLoginReq

from workouts.models import Workout, FilterPreference
from workouts.forms import graphrequestform


@swtLoginReq
def home(request):
	user = request.user.username
	user_exists = Profile.objects.filter(username=user)
	user_profile = Profile.objects.filter(username=user, completed=False)
	
	# Verify if New User
	if user_exists.count() < 1:
		profile = Profile(username=user)
		user_prefs = FilterPreference(username=user)
		profile.save()
		user_prefs.save()
		
		return HttpResponseRedirect('/swt/profiles/new/')
	# Verify if Incomplete User Profile
	elif user_profile.count() > 0:
		return HttpResponseRedirect('/swt/profiles/new/')
	else:
		profile = Profile.objects.get(username=user)    
  
	args = {}
	args.update(csrf(request))
	args['profile'] = profile

    # WORKOUTS ARGUMENTS
	args['workouts'] = Workout.objects.filter(username=user).order_by('-date')[0:5]

    # FRIENDLIST ARGUMENTS
	args['friends_accepted'] = FriendList.objects.filter(sender_id=user, accepted=True).order_by('receiver_id')
	args['friends_pending'] = FriendList.objects.filter(sender_id=user, accepted=False)
	args['friends_request'] = FriendList.objects.filter(receiver_id=user, accepted=False)
	args['friends_form'] = FriendsForm()
	
	# GYMSTATUS ARGUMENTS
	args['gym_status'] = GymStatus.objects.all()
	
	args['curr_weekday'] = strftime("%A")
	args['curr_hour'] = strftime("%H")
	

	return render_to_response('home-index.html', args)


@swtLoginReq
def myProfile(request):
	user = request.user.username

	args = {}
	args['profile'] = Profile.objects.get(username=user)
	args['user_auth'] = User.objects.get(username=user)
	args['my_chest_workouts'] = Workout.objects.filter(username=user, weights_type='CHEST').count()
	args['my_legs_workouts'] = Workout.objects.filter(username=user, weights_type='LEGS').count()
	args['my_back_workouts'] = Workout.objects.filter(username=user, weights_type='BACK').count()
	args['my_treadmill_workouts'] = Workout.objects.filter(username=user, cardio_type='TREADMILL').count()
	args['my_stairs_workouts'] = Workout.objects.filter(username=user, cardio_type='STAIRS').count()
	args['my_rowing_workouts'] = Workout.objects.filter(username=user, cardio_type='ROWING').count()
	today = datetime.date.today()

	form = graphrequestform()
	args.update(csrf(request))
	args['chartform'] = form


	weightworkoutdata = \
		DataPool(
			series =
				[{'options': {
					'source': Workout.objects.filter(username=user, weights_type='CHEST', month=today.month )},
						'terms': [
						{'day_chest': 'day'},
						{'Chest Weight': 'weight'}]},

					{'options': {
						'source': Workout.objects.filter(username=user, weights_type='LEGS', month=today.month )},
						'terms': [
						{'day_legs': 'day'},
						{'Legs Weight': 'weight'}]},

					{'options': {
						'source': Workout.objects.filter(username=user, weights_type='BACK', month=today.month )},
						'terms': [
						{'day_back': 'day'},
						{'Back Weight': 'weight'}]},
					])

	weightworkoutchart = Chart(
		datasource = weightworkoutdata,
			series_options =
				[{'options':{
				'type': 'column',
				'stacking': False},
				'terms': {
					'day_chest': [
						'Chest Weight'],
					'day_legs': [
						'Legs Weight'],
					'day_back': [
						'Back Weight'],
					}}],
			chart_options =
				{'title': {
					'text': ' '},
				'xAxis': {
					'title': {
						'text': 'Weights by Day'}}})

	cardioworkoutdata = \
		DataPool(
			series =
				[{'options': {
					'source': Workout.objects.filter(username=user, cardio_type='TREADMILL', month = today.month )},
					'terms': [
					{'day_treadmill': 'day'},
					{'Treadmill Duration': 'time'}]},

				{'options': {
					'source': Workout.objects.filter(username=user, cardio_type='STAIRS', month = today.month )},
					'terms': [
					{'day_stairs': 'day'},
					{'Stairs Duration': 'time'}]},

				{'options': {
					'source': Workout.objects.filter(username=user, cardio_type='ROWING', month = today.month )},
					'terms': [
					{'day_rowing': 'day'},
					{'Rowing Duration': 'time'}]},
				])

	cardioworkoutchart = Chart(
		datasource = cardioworkoutdata,
			series_options =
				[{'options':{
					'type': 'column',
					'stacking':False},
						'terms': {
							'day_treadmill': [
								'Treadmill Duration'],
							'day_stairs': [
								'Stairs Duration'],
							'day_rowing': [
								'Rowing Duration'],
							}}],
			chart_options =
			{'title': {
				'text': ' '},
			'xAxis': {
				'title': {
					'text':  'Workout Duration by Day'}}})

	
	charts = [cardioworkoutchart, weightworkoutchart]
	args['charts'] = charts
	args['cur_month'] = today.strftime('%B')
	
	# Profile Image hash
	signer = Signer()
	img_hash = signer.sign('p-img-' + user)
	args['img_hash'] = img_hash

	return render_to_response('profiles-index.html', args)


@swtLoginReq
def newProfile(request):
	user = request.user.username
	user_profile = Profile.objects.filter(username=user, completed=True)

	# Check if logged in user already has a completed profile
	if user_profile.count() > 0:
		return HttpResponseRedirect('/swt/')

	profile = Profile.objects.get(username=user)

	if request.POST:
		form = ProfileForm(request.POST, instance=profile)
			
		if form.is_valid():
			form.save()
			
			# Create hash name for profile image
			signer = Signer()
			img_hash = signer.sign('p-img-' + user)
		
			data = form.cleaned_data
			
			if data['profile_pic'] == '':
				folder = '/home/phoenix470/swt/media/static/assets/uploaded_files'
				imgurl = 'http://terryshoemaker.files.wordpress.com/2013/03/placeholder1.jpg'
				urllib.urlretrieve(imgurl, folder + '/' + img_hash + '.jpg')
			else:
				folder = '/home/phoenix470/swt/media/static/assets/uploaded_files'
				imgurl = data['profile_pic']
				urllib.urlretrieve(imgurl, folder + '/' + img_hash + '.jpg')
				
			profile.completed = True
			profile.save()

			return HttpResponseRedirect('/swt/')
	else:
		form = ProfileForm()

	args = {}
	args.update(csrf(request))
	
	args['form'] = form

	return render_to_response('profile-new.html', args)


@swtLoginReq
def editProfile(request):
	user = request.user.username
	profile = Profile.objects.get(username=user)

	if request.POST:
		form = ProfileForm(request.POST, request.FILES, instance=profile)
		
		if form.is_valid():
			form.save()
			
			# create hash name for profile image
			signer = Signer()
			img_hash = signer.sign('p-img-' + user)
			
			data = form.cleaned_data
			
			if data['profile_pic'] == '':
				folder = '/home/phoenix470/swt/media/static/assets/uploaded_files'
				imgurl = 'http://terryshoemaker.files.wordpress.com/2013/03/placeholder1.jpg'
				urllib.urlretrieve(imgurl, folder + '/' + img_hash + '.jpg')
			else:
				folder = '/home/phoenix470/swt/media/static/assets/uploaded_files'
				imgurl = data['profile_pic']
				urllib.urlretrieve(imgurl, folder + '/' + img_hash + '.jpg')
			
			return HttpResponseRedirect('/swt/profiles/')

	else:
		form = ProfileForm(instance=profile)

	args = {}
	args.update(csrf(request))

	args['form'] = form

	return render_to_response('profile-edit.html', args)


@swtLoginReq
def requestFriend(request):
	user = request.user.username

	if request.POST:
		friend_request = FriendList(sender_id=user)
		form = FriendsForm(request.POST, instance=friend_request)
		if form.is_valid():
			data = form.cleaned_data
			receiver_id = data['receiver_id']
			
			# Check if User exists
			requested_user = Profile.objects.filter(username=receiver_id)
			request_check = FriendList.objects.filter(sender_id=user, receiver_id=receiver_id)
			friend_check = FriendList.objects.filter(sender_id=receiver_id, receiver_id=user)
			
			if (requested_user.count() < 1 or request_check.count() >= 1 or friend_check.count() >= 1):
				# Send to User A;ready Requested
				return HttpResponseRedirect('/swt/')
			else:
				form.save()

	return HttpResponseRedirect('/swt/')


@swtLoginReq
def acceptFriend(request, friend_id):
	user = request.user.username
	friend_request = FriendList.objects.get(sender_id=friend_id, receiver_id=user, accepted=False)
    
	if friend_request != None:
		friend_request.accepted = True
		friend_request.save()
	
	friend_new = FriendList(sender_id=user, receiver_id=friend_id, accepted=True)
	friend_new.save()
	
	return HttpResponseRedirect('/swt/')


@swtLoginReq
def declineFriend(request, friend_id):
    user = request.user.username
    friend_request = FriendList.objects.get(sender_id=friend_id, receiver_id=user, accepted=False)
    if friend_request != None:
		friend_request.delete()

    return HttpResponseRedirect('/swt/')


@swtLoginReq
def deleteFriend(request, friend_id):
	user = request.user.username
	friend_del1 = FriendList.objects.get(sender_id=user, receiver_id=friend_id, accepted=True)
	friend_del2 = FriendList.objects.get(sender_id=friend_id, receiver_id=user, accepted=True)

	if friend_del1 != None:
		friend_del1.delete()
	if friend_del2 != None:
		friend_del2.delete()

	return HttpResponseRedirect('/swt/')


@swtLoginReq
def viewFriend(request, friend_id):
	user = request.user.username
	
	friend = FriendList.objects.get(sender_id=user, receiver_id=friend_id, accepted=True)

	if friend != None:
		friend_profile = Profile.objects.get(username=friend_id)
		
		
		args = {}
		args['profile'] = friend_profile
		args['user_auth'] = User.objects.get(username=friend_id)
		
		# Friend WORKOUT Arguments
		args['my_chest_workouts'] = Workout.objects.filter(username=friend_id, weights_type='CHEST').count()

profiles/templates/home-index.html
{% extends "base-default.html" %}
{% load static %}


<!-- Header Content Block
================================================== -->


<!-- Main Content Block After Navigation
================================================== -->
{% block content %}
<div class="container-fluid">
	<div class="row-fluid">

		<!-- Column: Left -->
		<div class="col-md-9">
			<!-- Introductory -->
			<h1>Welcome to the SFU Workout Tracker</h1>
			<h2>Hi, {{ profile.first_name|title }} {{ profile.last_name|title }}.</h2>
			<p>Within the heart of Simon Fraser University, the Recreation Center provides students and community with a fun, friendly, and motivated environment to get yourself moving and enjoy being fit.</p>

			<blockquote>
				<p>People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.</p>
				<small>Zig Ziglar</small>
			</blockquote>

			<h3>Using SFU Workout Tracker</h3>

			<p>If you don't track, how do you know if you're improving? Track all your activities, whether that's weight-lifting, running the treadmill, or even enjoying watch yourself skiprope through the mirror. By tracking your progress, you'll be able to learn more about which types of activities you focus on at the gym, be able to set and organize your next workout, and just purely show off and tell others about your process!</p>
			
			<p>Using <strong>SFU Workout Tracker</strong>, you'll be able to submit and track each workout that you do and look back on it. Have friends that go to the gym too? Add them! Keep an eye on your progress and how all your friends and community are doing with some nifty performance graphs. You can even book equipment through SWT so that you can ensure the equipment will be availble to you when you arrive.</p>
		
			<div class="panel panel-primary mar-top-25">
				<div class="panel-heading">
					<h3 class="panel-title">Recent Workouts</h3>
				</div>
				<div class="panel-body">
					<table class="table table-striped table-bordered table-hover">
						{% if workouts|length = 0 %}
							<tr><td><span>None</span></td></tr>
						{% else %}
							{% for workout in workouts %}
							<tr>
								<td>
								{% if workout.style = 'Weights Workout' %}
								<h3 class="neg-mar-top-3">{{ workout.style }} - {{ workout.weights_type }}</h3>
								<ul>
									<li><b>Date Completed:</b> {{ workout.date }}</li>
									<li><b>Weight:</b> {{ workout.weight }} kg</li>
									<li><b>No. of Sets:</b> {{ workout.sets }}</li>
									<li><b>No. of Reps:</b> {{ workout.reps }} </li>
								</ul>

								{% elif workout.style = 'Cardio Workout' %}
								<h3 class="neg-mar-top-3">{{ workout.style }} - {{ workout.cardio_type }}</h3>
								<ul>
									<li><b>Date Completed:</b> {{ workout.date }}</li>
									<li><b>Speed:</b> {{ workout.speed }} km/h</li>
									<li><b>Duration:</b> {{ workout.time }} minutes</li>	
								</ul>
								{% endif %}
								</td>
							</tr>
							{% endfor %}
						{% endif %}
					</table>
				</div>
			</div>

		</div>

		<!-- Column: Right -->
		<div class="col-md-3">
			<!-- General Information -->
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">General Inforamtion</h3>
				</div>
				<div class="panel-body">
					<h4>Location</h4>
					<p class="pad-bot-5 pad-sides-5">The Burnaby campus's Rec facilities are on the west side of the campus near the West Mall Complex (WMX) and just before Residence and Housing. There are access points to the main Lorne Davies Complex from all levels.</p>

					<h4>Facility Hours</h4>
					<p class="pad-sides-5">
						<b>Monday to Friday:</b> 8:00am-6:00pm<br />
						<b>Weekends:</b> 10:00am-5:00pm<br/>
						<b>Holidays:</b> Closed<br/>
					</p>
					<h4>Facility Status</h4>
					<table class="pad-sides-5">
						{% for location in gym_status %}
						<tr>
							<td>
								{% if curr_weekday == 'Saturday' or curr_weekday == 'Sunday' %}
									{% if curr_hour >= 11 and curr_hour <= 13 %}
									<img src="{% static "assets/img/red-circle-icon.png" %}" alt="red">
									{% elif curr_hour >= 10 and curr_hour <= 17 %}
									<img src="{% static "assets/img/green-circle-icon.png" %}" alt="green">
									{% elif curr_hour < 10 or curr_hour > 17 %}
									<img src="{% static "assets/img/gray-circle-icon.png" %}" alt="gray">
									{% endif %}
								{% else %}
									{% if curr_hour >= 10 and curr_hour <= 13 %}
									<img src="{% static "assets/img/red-circle-icon.png" %}" alt="red">
									{% elif curr_hour >= 8 and curr_hour <= 18 %}
									<img src="{% static "assets/img/green-circle-icon.png" %}" alt="green">
									{% elif curr_hour < 8 or curr_hour > 18 %}
									<img src="{% static "assets/img/gray-circle-icon.png" %}" alt="gray">
									{% endif %}
								{% endif %}
							</td>
							<td class="pad-sides-5">{{ location.gym_area }}</td>
						</tr>
						{% endfor %}
					</table>
				
				</div>
			</div>

			<!-- Friend List -->
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Friend List</h3>
				</div>
				<div class="panel-body">
					<div class="pad-bot-5">
						<h4>Requests</h4>
						<ul>
							{% if friends_request|length = 0 %}
							<li>None</li>
							{% else %}
								{% for request in friends_request %}
								<li>{{ request.sender_id }} - <a href="/swt/profiles/friend-accept/{{ request.sender_id }}/"><span class="label label-success">Accept</span></a> <a href="/swt/profiles/friend-decline/{{ request.sender_id }}/"><span class="label label-danger">Decline</span></a></li>
								{% endfor %}
							{% endif %}
						</ul>
					</div>
					
					<div class="pad-bot-5">
						<h4>Friends</h4>
						{% if friends_accepted|length = 0 and friends_pending|length = 0 %}
						<ul><li>None</li></ul>
						{% else %}
						<table>
							{% for friend in friends_accepted %}
							<tr>
								<td><img src="{% static "assets/img/approved-icon.png" %}" alt="approved"></td>
								<td class="pad-sides-5"><strong>{{ friend.receiver_id }}</strong></td>
								<td class="pad-sides-5">
									<span class="label label-primary pad-sides-5"><a class="txt-white" href="/swt/friends/{{ friend.receiver_id }}/">View Profile</a></span>
									<span class="label label-info pad-sides-5"><a class="txt-white" href="/swt/profiles/friend-decline/{{ request.sender_id }}/">Unfriend</a></span>
								</td>
							</tr>
							{% endfor %}
							{% for friend in friends_pending %}
							<tr>
								<td><img src="{% static "assets/img/pending-icon.png" %}" alt="pending"></td>
								<td class="pad-sides-5">{{ friend.receiver_id }}</td>
							</tr>
							{% endfor %}
						</table>
						{% endif %}
					</div>					
					
					<div>
						<h4>Add Friend</h4>
						<form action="/swt/profiles/friend-request/" method="post">{% csrf_token %}
							<span><b>Friend Id:</b></span> 
							<p>{{ friends_form.receiver_id }}</p>
							<input type="submit" name="submit" value="Add Friend" class="btn btn-primary btn-xs">
						</form>
					</div>

				</div>
			</div>
		</div>

	</div>
</div>
{% endblock %}

profiles/templates/profile-edit.html
{% extends "base-default.html" %}
<!-- Main Content Block After Navigation
================================================== -->
{% block content %}
<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-md-12">
            <!-- Edit Contact Profile Creation -->
            <h1>Edit Profile</h1>

            <form class="form-horizontal" action="/swt/profiles/edit/" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="form-group">
                    <label for="id_first_name" class="col-md-1 control-label">First Name</label>
                    <div class="col-md-5">{{ form.first_name }}</div>
                </div>
                <div class="form-group">
                    <label for="id_last_name" class="col-md-1 control-label">Last Name</label>
                    <div class="col-md-5">{{ form.last_name }}</div>
                </div>
                <div class="form-group">
                    <label for="id_weight" class="col-md-1 control-label">Weight</label>
                    <div class="col-md-5">{{ form.weight }}</div>
                </div>
                <div class="form-group">
                    <label for="id_height" class="col-md-1 control-label">Height</label>
                    <div class="col-md-5">{{ form.height }}</div>
                </div>
                <div class="form-group">
                    <label for="id_bio" class="col-md-1 control-label">Biography</label>
                    <div class="col-md-5">{{ form.bio }}</div>
                </div>
                <div class="form-group">
                    <label for="id_quote" class="col-md-1 control-label">Quote</label>
                    <div class="col-md-5">{{ form.quote }}</div>
                </div>
				
				<div class="form-group">
					<label for="id_image" class="col-md-1 control-label">Image URL</label>
					<div class="col-md-5">{{ form.profile_pic }}</div>
				</div>
				
				<div class="form-group">
				    <div class="col-md-10 col-md-offset-5">
					<input class="btn btn-primary btn-sm" type="submit" name="submit" value="Submit Profile Change">
            		</div>
				</div>
			
			</form>
        </div>
    </div>
</div>
{% endblock %}

profiles/templates/profile-new.html
{% extends "base-form.html" %}
<!-- Main Content Block After Navigation
================================================== -->
{% block content %}
<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-md-12">
            <!-- New Contact Profile Creation -->
            <h1>New Profile</h1>

            <form class="form-horizontal" action="/swt/profiles/new/" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="form-group">
                    <label for="id_first_name" class="col-md-1 control-label">First Name</label>
                    <div class="col-md-5">{{ form.first_name }}</div>
                </div>
                <div class="form-group">
                    <label for="id_last_name" class="col-md-1 control-label">Last Name</label>
                    <div class="col-md-5">{{ form.last_name }}</div>
                </div>
                <div class="form-group">
                    <label for="id_weight" class="col-md-1 control-label">Weight (kg)</label>
                    <div class="col-md-5">{{ form.weight }}</div>
                </div>
                <div class="form-group">
                    <label for="id_height" class="col-md-1 control-label">Height (cm)</label>
                    <div class="col-md-5">{{ form.height }}</div>
                </div>
                <div class="form-group">
                    <label for="id_bio" class="col-md-1 control-label">Biography</label>
                    <div class="col-md-5">{{ form.bio }}</div>
                </div>
                <div class="form-group">
                    <label for="id_quote" class="col-md-1 control-label">Quote</label>
                    <div class="col-md-5">{{ form.quote }}</div>
                </div>
				
				<div class="form-group">
					<label for="id_image" class="col-md-1 control-label">Image URL</label>
					<div class="col-md-5">{{ form.profile_pic }}</div>
				</div>

				<div class="form-group">
				    <div class="col-md-10 col-md-offset-5">
					<input class="btn btn-primary btn-sm" type="submit" name="submit" value="Create Profile">
            		</div>
				</div>
			
			</form>
        </div>
    </div>
</div>
{% endblock %}